from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class UserScenario:
    """Documented user scenario for coverage tracking."""

    id: str
    domain: str
    preconditions: str
    actions: str
    expected: str
    persisted: str
    events: str
    metrics: str
    test_tier: str  # unit | integration | e2e
    automated: bool = False


USER_SCENARIOS: tuple[UserScenario, ...] = (
    UserScenario(
        id="import.apple.stream",
        domain="import",
        preconditions="Bridge runtime, Apple gateway registered, mocked import port",
        actions="import_playlist stream with 1 track",
        expected="ImportResultState phase=completed, track ADDED",
        persisted="history session JSON (if enabled), identity cache optional",
        events="progress + diagnostic bridge events",
        metrics="perf_span optional",
        test_tier="integration",
        automated=True,
    ),
    UserScenario(
        id="import.youtube.file",
        domain="import",
        preconditions="Snapshot JSON/CSV file on disk",
        actions="load_remote_playlist_from_file",
        expected="RemotePlaylistSnapshot parsed, provider_id set",
        persisted="none until import_remote_playlist",
        events="none",
        metrics="none",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="import.file.remote",
        domain="import",
        preconditions="Isolated tmp repository",
        actions="import_remote_playlist via bridge",
        expected="ManagedPlaylistDetail origin=provider_library",
        persisted="managed_playlists.json + snapshot archive",
        events="none",
        metrics="none",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="create.local.repository",
        domain="repository",
        preconditions="Empty repository",
        actions="import remote snapshot or migrate history",
        expected="local_playlist_id assigned, version=1",
        persisted="managed_playlists.json",
        events="none",
        metrics="none",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="snapshot.archive",
        domain="snapshots",
        preconditions="RemotePlaylistSnapshot checksum",
        actions="store same snapshot twice",
        expected="Single file in snapshots dir",
        persisted="data/snapshots/snap-<checksum>.json",
        events="none",
        metrics="none",
        test_tier="unit",
        automated=True,
    ),
    UserScenario(
        id="sync.dry_run",
        domain="sync",
        preconditions="Local + remote snapshots in params",
        actions="plan_sync sync_mode=dry_run",
        expected="sync_plan actions, no mutation",
        persisted="sync_operations.json unchanged",
        events="sync.plan.completed",
        metrics="observability duration_ms, actions_total",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="sync.apply.append",
        domain="sync",
        preconditions="Plan checksum, matching versions, write port",
        actions="apply_sync push append_only",
        expected="operation COMPLETED, playlist synced",
        persisted="sync_operations.json, managed_playlists.json",
        events="sync.apply.started/completed",
        metrics="observability success counts",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="sync.partial_failure",
        domain="sync",
        preconditions="Write port fails on second action",
        actions="apply_sync with failing write port",
        expected="PARTIAL or FAILED operation",
        persisted="sync_operations.json with failed_actions",
        events="sync.apply.failed or completed with actions_failed>0",
        metrics="failure_counts",
        test_tier="integration",
        automated=True,
    ),
    UserScenario(
        id="sync.conflicts.resolve",
        domain="sync",
        preconditions="Conflicting local/remote metadata",
        actions="plan_sync manual_resolve then resolve_sync_conflicts",
        expected="new plan_checksum after resolution",
        persisted="none until apply",
        events="sync.plan.completed",
        metrics="conflicts_total in plan event",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="history.migration",
        domain="history",
        preconditions="History session with import outcomes",
        actions="list_managed_playlists triggers migration",
        expected="hist-* playlist in repository view",
        persisted="managed_playlists.json after first list",
        events="none",
        metrics="none",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="observability.diagnostics",
        domain="observability",
        preconditions="Observability bus active",
        actions="diagnostics command after sync plan",
        expected="observability.health + metrics + sync_timeline",
        persisted="in-memory bus only",
        events="system.health_check",
        metrics="event_count, average_duration_ms",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="plugins.extension_points",
        domain="plugins",
        preconditions="Platform package loaded",
        actions="diagnostics snapshot",
        expected="extension_points + extension_api_version in summary",
        persisted="none",
        events="none",
        metrics="none",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="providers.list",
        domain="providers",
        preconditions="Apple + YouTube gateways registered",
        actions="list_providers",
        expected="apple_music available, youtube experimental flag",
        persisted="none",
        events="none",
        metrics="none",
        test_tier="e2e",
        automated=True,
    ),
    UserScenario(
        id="errors.invalid_bridge",
        domain="errors",
        preconditions="Bridge JSON-RPC",
        actions="malformed command or missing params",
        expected="ok=false, BridgeErrorCode",
        persisted="none",
        events="diagnostic error events optional",
        metrics="none",
        test_tier="unit",
        automated=True,
    ),
    UserScenario(
        id="resume.import.checkpoint",
        domain="resume",
        preconditions="Import checkpoint mid-stream",
        actions="resume import_stream from checkpoint",
        expected="remaining tracks processed",
        persisted="import session store",
        events="progress events",
        metrics="none",
        test_tier="integration",
        automated=True,
    ),
    UserScenario(
        id="migration.history_idempotent",
        domain="migration",
        preconditions="Same history session listed twice",
        actions="list_managed_playlists x2",
        expected="single migrated playlist",
        persisted="managed_playlists.json stable",
        events="none",
        metrics="none",
        test_tier="unit",
        automated=True,
    ),
    UserScenario(
        id="generation.catalog",
        domain="generation",
        preconditions="iTunes catalog reachable or mocked",
        actions="generate_playlist via bridge",
        expected="PlaylistGenerationResult with sections",
        persisted="history session optional",
        events="none",
        metrics="none",
        test_tier="integration",
        automated=False,
    ),
    UserScenario(
        id="import.apple.real",
        domain="import",
        preconditions="macOS + Music.app",
        actions="Full Apple Music import",
        expected="Tracks in library",
        persisted="library + history",
        events="full diagnostic stream",
        metrics="perf traces",
        test_tier="e2e",
        automated=False,
    ),
)

AUTOMATED_SCENARIO_IDS: frozenset[str] = frozenset(
    scenario.id for scenario in USER_SCENARIOS if scenario.automated
)
