from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

from playlist_builder.core.models import TrackRef


class EnergyProfile(str, Enum):
    CHILL = "chill"
    STEADY = "steady"
    RISING = "rising"
    PARTY = "party"


@dataclass(frozen=True)
class SeedTrack:
    track: TrackRef
    weight: float = 1.0


@dataclass(frozen=True)
class GenerationConstraints:
    target_track_count: int | None = None
    target_duration_minutes: int | None = None
    energy_profile: EnergyProfile = EnergyProfile.RISING
    excluded_terms: tuple[str, ...] = ()
    preferred_terms: tuple[str, ...] = ()
    allow_explicit: bool = True

    def validate(self) -> None:
        if self.target_track_count is None and self.target_duration_minutes is None:
            raise ValueError("Une génération doit définir un nombre de morceaux ou une durée cible.")
        if self.target_track_count is not None and self.target_track_count <= 0:
            raise ValueError("Le nombre de morceaux cible doit être positif.")
        if self.target_duration_minutes is not None and self.target_duration_minutes <= 0:
            raise ValueError("La durée cible doit être positive.")


@dataclass(frozen=True)
class PlaylistRequest:
    name: str
    seeds: tuple[SeedTrack, ...]
    constraints: GenerationConstraints
    description: str = "Generated by Apple Music Playlist Builder"

    def validate(self) -> None:
        if not self.name.strip():
            raise ValueError("Le nom de la playlist est obligatoire.")
        if not self.seeds:
            raise ValueError("Au moins un morceau de référence est requis.")
        self.constraints.validate()


@dataclass(frozen=True)
class CandidateTrack:
    track: TrackRef
    score: float
    source: str = "unknown"
    reasons: tuple[str, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class GeneratedPlaylist:
    request: PlaylistRequest
    candidates: tuple[CandidateTrack, ...]

    @property
    def tracks(self) -> list[TrackRef]:
        return [candidate.track for candidate in self.candidates]
