from __future__ import annotations

import json
import os
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any

from playlist_builder.core.models import TrackAddResult, TrackAddStatus, TrackRef

API_BASE = "https://api.music.apple.com/v1"


class MusicKitConfigurationError(RuntimeError):
    pass


@dataclass(frozen=True)
class MusicKitCredentials:
    developer_token: str
    user_token: str

    @classmethod
    def from_env(cls) -> "MusicKitCredentials":
        developer_token = os.getenv("APPLE_MUSIC_DEVELOPER_TOKEN", "").strip()
        user_token = os.getenv("APPLE_MUSIC_USER_TOKEN", "").strip()
        if not developer_token or not user_token:
            raise MusicKitConfigurationError(
                "MusicKit nécessite APPLE_MUSIC_DEVELOPER_TOKEN et APPLE_MUSIC_USER_TOKEN."
            )
        return cls(developer_token=developer_token, user_token=user_token)


class MusicKitClient:
    """Apple Music API client.

    This client intentionally supports create/update only. It does not expose playlist
    deletion because the product direction explicitly excludes destructive actions.
    """

    def __init__(self, credentials: MusicKitCredentials, storefront: str = "us") -> None:
        self.credentials = credentials
        self.storefront = storefront

    @classmethod
    def from_env(cls, storefront: str = "us") -> "MusicKitClient":
        return cls(MusicKitCredentials.from_env(), storefront=storefront)

    def create_or_update_playlist(
        self,
        name: str,
        tracks: list[TrackRef],
        *,
        description: str = "Generated by Apple Music Playlist Builder",
    ) -> list[TrackAddResult]:
        song_ids: list[tuple[TrackRef, str | None, str]] = []
        for track in tracks:
            song_id, error = self.find_song_id(track)
            song_ids.append((track, song_id, error))

        found_ids = [song_id for _, song_id, _ in song_ids if song_id]
        playlist_id = self.find_library_playlist_id_by_name(name)

        if playlist_id is None:
            playlist_id = self.create_library_playlist(name, description, found_ids)
        elif found_ids:
            self.add_tracks_to_library_playlist(playlist_id, found_ids)

        results: list[TrackAddResult] = []
        for track, song_id, error in song_ids:
            if song_id:
                results.append(TrackAddResult(track=track, status=TrackAddStatus.ADDED))
            else:
                results.append(TrackAddResult(track=track, status=TrackAddStatus.NOT_FOUND, error=error))
        return results

    def find_song_id(self, track: TrackRef) -> tuple[str | None, str]:
        term = f"{track.artist} {track.title}"
        query = urllib.parse.urlencode({"term": term, "types": "songs", "limit": "10"})
        data = self._request_json("GET", f"/catalog/{self.storefront}/search?{query}")
        candidates = data.get("results", {}).get("songs", {}).get("data", [])
        best = self._pick_best(track, candidates)
        if not best:
            return None, "Aucune correspondance MusicKit fiable."
        return best.get("id"), ""

    def find_library_playlist_id_by_name(self, name: str) -> str | None:
        next_path = "/me/library/playlists?limit=100"
        while next_path:
            data = self._request_json("GET", next_path)
            for playlist in data.get("data", []):
                if playlist.get("attributes", {}).get("name") == name:
                    return playlist.get("id")
            next_path = data.get("next")
        return None

    def create_library_playlist(self, name: str, description: str, song_ids: list[str]) -> str:
        payload: dict[str, Any] = {
            "attributes": {
                "name": name,
                "description": description,
            }
        }
        if song_ids:
            payload["relationships"] = {
                "tracks": {
                    "data": [{"id": song_id, "type": "songs"} for song_id in song_ids]
                }
            }
        data = self._request_json("POST", "/me/library/playlists", payload)
        playlist_id = data.get("data", [{}])[0].get("id") or data.get("id")
        if not playlist_id:
            raise RuntimeError("MusicKit n'a pas renvoyé l'identifiant de la playlist créée.")
        return playlist_id

    def add_tracks_to_library_playlist(self, playlist_id: str, song_ids: list[str]) -> None:
        # No deletion is supported. Update means append missing/candidate tracks only.
        for offset in range(0, len(song_ids), 100):
            chunk = song_ids[offset : offset + 100]
            payload = {"data": [{"id": song_id, "type": "songs"} for song_id in chunk]}
            self._request_json("POST", f"/me/library/playlists/{playlist_id}/tracks", payload)

    def _request_json(self, method: str, path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:
        url = path if path.startswith("http") else f"{API_BASE}{path}"
        body = json.dumps(payload).encode("utf-8") if payload is not None else None
        request = urllib.request.Request(url, data=body, method=method)
        request.add_header("Authorization", f"Bearer {self.credentials.developer_token}")
        request.add_header("Music-User-Token", self.credentials.user_token)
        request.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                raw = response.read().decode("utf-8")
                return json.loads(raw) if raw else {}
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"MusicKit HTTP {exc.code}: {detail}") from exc

    @staticmethod
    def _pick_best(track: TrackRef, candidates: list[dict[str, Any]]) -> dict[str, Any] | None:
        scored = sorted(candidates, key=lambda item: MusicKitClient._score(track, item), reverse=True)
        if not scored:
            return None
        return scored[0] if MusicKitClient._score(track, scored[0]) >= 60 else None

    @staticmethod
    def _score(track: TrackRef, item: dict[str, Any]) -> int:
        attributes = item.get("attributes", {})
        artist = attributes.get("artistName", "").lower()
        title = attributes.get("name", "").lower()
        wanted_artist = track.artist.lower()
        wanted_title = track.title.lower()
        score = 0
        if wanted_artist == artist:
            score += 50
        elif wanted_artist in artist or artist in wanted_artist:
            score += 30
        if wanted_title == title:
            score += 50
        elif wanted_title in title or title in wanted_title:
            score += 30
        return score
