from __future__ import annotations

import argparse
import sys
from pathlib import Path

from playlist_builder.catalog.apple_search import AppleCatalogSearch
from playlist_builder.catalog.cache import JsonCache
from playlist_builder.catalog.rate_limiter import RateLimiter
from playlist_builder.cli.generate_args import (
    build_playlist_request,
    parse_csv_terms,
    parse_energy_profile,
)
from playlist_builder.discovery.itunes_provider import ITunesCandidateProvider
from playlist_builder.discovery.pipeline import DiscoveryPipeline
from playlist_builder.discovery.providers import StaticCandidateProvider
from playlist_builder.playlists.exporter import write_generated_playlist
from playlist_builder.session.engine import GenerationSessionEngine

DEFAULT_OUTPUT = Path("playlists/generated_playlist.json")
DEFAULT_CACHE = Path("cache/itunes_catalog.json")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate an Apple Music playlist JSON from seeds and keywords."
    )
    parser.add_argument("--name", default="Generated Playlist", help="Playlist name.")
    parser.add_argument(
        "--seed",
        action="append",
        default=[],
        metavar="ARTIST:TITLE",
        help="Reference track. Repeatable. Formats: 'Kygo:Firestone' or 'Kygo - Firestone'.",
    )
    parser.add_argument(
        "--keywords",
        "--keyword",
        dest="keywords",
        default="",
        help="Comma-separated preferred terms, e.g. 'tropical,dance'.",
    )
    parser.add_argument(
        "--exclude",
        action="append",
        default=[],
        metavar="TERM",
        help="Exclusion rule. Repeatable. Optional kind prefix, e.g. 'artist:Pitbull'.",
    )
    parser.add_argument(
        "--include",
        action="append",
        default=[],
        metavar="TERM",
        help="Inclusion rule. Repeatable. Optional kind prefix, e.g. 'genre:OST'.",
    )
    parser.add_argument("--tracks", type=int, help="Target number of tracks.")
    parser.add_argument("--duration", type=int, help="Target duration in minutes.")
    parser.add_argument(
        "--energy",
        default=EnergyProfileDefault.RISING,
        help="Energy profile: chill, steady, rising, party, max_from_start, random.",
    )
    parser.add_argument("--country", default="us", help="Store country for catalog discovery, e.g. us, ch, fr.")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output JSON path compatible with create_playlist.py.",
    )
    parser.add_argument(
        "--description",
        default="Generated by Apple Music Playlist Builder",
        help="Playlist description stored in the exported JSON.",
    )
    parser.add_argument(
        "--cache",
        type=Path,
        default=DEFAULT_CACHE,
        help="JSON cache file for iTunes catalog lookups.",
    )
    parser.add_argument("--no-cache", action="store_true", help="Disable catalog response caching.")
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.5,
        help="Minimum delay between catalog API calls in seconds.",
    )
    parser.add_argument(
        "--no-catalog",
        action="store_true",
        help="Skip catalog discovery and keep seeds only.",
    )
    parser.add_argument(
        "--no-explicit",
        action="store_true",
        help="Exclude explicit tracks when metadata is available.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print results without writing JSON.")
    parser.add_argument(
        "--report",
        type=Path,
        help="Optional path for the mad-scientist generation report.",
    )
    return parser


class EnergyProfileDefault:
    RISING = "rising"


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)

    try:
        request = build_playlist_request(
            name=args.name,
            seeds=args.seed,
            keywords=parse_csv_terms(args.keywords),
            excludes=tuple(args.exclude),
            includes=tuple(args.include),
            track_count=args.tracks,
            duration_minutes=args.duration,
            energy_profile=parse_energy_profile(args.energy),
            allow_explicit=not args.no_explicit,
            description=args.description,
        )
    except ValueError as exc:
        print(f"Paramètres invalides: {exc}", file=sys.stderr)
        return 1

    engine, cache = _build_engine(args)
    print(f"🧪 Génération: {request.name}")
    print(f"🌱 Seeds: {len(request.seeds)}")
    if args.no_catalog:
        print("🔕 Découverte catalogue désactivée")
    else:
        print(f"🔎 Découverte catalogue: pays={args.country}")

    try:
        session = engine.generate(request)
    finally:
        if cache:
            cache.flush()

    generated = session.generated_playlist
    print(f"🎵 Morceaux sélectionnés: {len(generated.tracks)}")
    print(f"🧾 Rapport:\n{session.report}")

    for index, track in enumerate(generated.tracks, 1):
        print(f"{index:03d}. {track.label}")

    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(session.report, encoding="utf-8")
        print(f"📄 Rapport sauvegardé: {args.report}")

    if args.dry_run:
        print("\nDry-run: aucun fichier JSON écrit.")
        return 0

    output_path = write_generated_playlist(generated, args.output)
    print(f"\n✅ Playlist exportée: {output_path}")
    print(f"➡️  Prochaine étape: python3 create_playlist.py --playlist {output_path}")
    return 0


def _build_engine(args: argparse.Namespace) -> tuple[GenerationSessionEngine, JsonCache | None]:
    if args.no_catalog:
        return GenerationSessionEngine(DiscoveryPipeline([StaticCandidateProvider([])])), None

    cache = None if args.no_cache else JsonCache(args.cache)
    search = AppleCatalogSearch(
        country=args.country,
        cache=cache,
        rate_limiter=RateLimiter(minimum_interval_seconds=max(0.0, args.sleep)),
    )
    return GenerationSessionEngine(DiscoveryPipeline([ITunesCandidateProvider(search)])), cache


if __name__ == "__main__":
    raise SystemExit(main())
